vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /build/images
            upload_destination: '%kernel.project_dir%/assets/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false
