controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

suecurity_controller:
    resource: ../../src/Controller/SecurityController.php
    type: annotation

vue_controller:
    resource: ../../src/Controller/HomePageController.php
    type: annotation